name: Tests

on: [push]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Bogdanp/setup-racket@v1.9
        with:
          version: 8.7
      - run: raco pkg install -j 2 --auto
      - working-directory: ./test
        run: npm install escodegen
      - run: raco test -j 2 -c ee-lib
